spring:
  application:
    name: INCLOVE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 0
    locations: classpath:db/migration
    default-schema: inclove
    create-schemas: true
  sql:
    init:
      mode: never
  data:
    redis:
      host: 43.133.38.194
      port: 6379
      password: redis_HdXwZJ

logging:
  file:
    name: ./app.log
  logback:
    rollingPolicy:
      max-file-size: 50MB
      max-history: 14
      total-size-cap: 2GB
      clean-history-on-start: true
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    org.zalando.logbook: TRACE
    org.springframework.security: DEBUG


resend:
  api-key: ${RESEND_API_KEY}
  from: ${FROM}

google:
  client-id: ${GOOGLE_CLIENT_ID}

embeddings:
  apiKey: ${EMBEDDINGS_API_KEY}
  baseUrl: ${EMBEDDINGS_BASE_URL:https://dashscope.aliyuncs.com/compatible-mode/v1}
  model: ${EMBEDDINGS_MODEL:text-embedding-v4}
  vectorDimension: ${EMBEDDINGS_VECTOR_DIMENSION:1024}

milvus:
  dbName: ${MILVUS_DBNAME}
  uri: ${MILVUS_URI}
  token: ${MILVUS_TOKEN:root:Milvus}
  profileCollectionName: ${MILVUS_PROFILE_COLLECTION_NAME}
  queryCollectionName: ${MILVUS_QUERY_COLLECTION_NAME}

logbook:
  minimum-status: 0
  filter:
    enabled: false
  secure-filter:
    enabled: false

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson2
      broadcastChannel: projectA
      valueEncoder: kryo5
      valueDecoder: kryo5
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}



